# CodeFactor configuration
# Exclude generated and build artifacts, tests, and benchmarks
exclude_paths:
  - "**/bin/**"
  - "**/obj/**"
  - "**/artifacts/**"
  - "tests/**"
  - "benchmarks/**"

# Alternative ignore patterns for duplication analysis
ignore_patterns:
  - "benchmarks/**"

# Enable language-specific engines if supported by CodeFactor
engines:
  csharp:
    enabled: true

# You can customize further rules here. See CodeFactor docs for options.
